// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_liteGreyBG;
lv_obj_t * ui_textLable;
lv_obj_t * ui_busBackBorder;
lv_obj_t * ui_seatContainerDriver;
lv_obj_t * ui_seatGUI;
lv_obj_t * ui_seatContainer1C;
lv_obj_t * ui_seatGUI1C;
lv_obj_t * ui_Label1C;
lv_obj_t * ui_seatContainer2C;
lv_obj_t * ui_seatGUI2C;
lv_obj_t * ui_Label2C;
lv_obj_t * ui_seatContainer4C;
lv_obj_t * ui_seatGUI4C;
lv_obj_t * ui_Label4C;
lv_obj_t * ui_seatContainer3C;
lv_obj_t * ui_seatGUI3C;
lv_obj_t * ui_Label3C;
lv_obj_t * ui_seatContainer5C;
lv_obj_t * ui_seatGUI5C;
lv_obj_t * ui_Label5C;
lv_obj_t * ui_seatContainer6C;
lv_obj_t * ui_seatGUI6C;
lv_obj_t * ui_Label6C;
lv_obj_t * ui_seatContainer7C;
lv_obj_t * ui_seatGUI7C;
lv_obj_t * ui_Label7C;
lv_obj_t * ui_seatContainer1B;
lv_obj_t * ui_seatGUI1B;
lv_obj_t * ui_Label1B;
lv_obj_t * ui_seatContainer2B;
lv_obj_t * ui_seatGUI2B;
lv_obj_t * ui_Label2B;
lv_obj_t * ui_seatContainer3B;
lv_obj_t * ui_seatGUI3B;
lv_obj_t * ui_Label3B;
lv_obj_t * ui_seatContainer4B;
lv_obj_t * ui_seatGUI4B;
lv_obj_t * ui_Label4B;
lv_obj_t * ui_seatContainer5B;
lv_obj_t * ui_seatGUI5B;
lv_obj_t * ui_Label5B;
lv_obj_t * ui_seatContainer6B;
lv_obj_t * ui_seatGUI6B;
lv_obj_t * ui_Label6B;
lv_obj_t * ui_seatContainer7B;
lv_obj_t * ui_seatGUI7B;
lv_obj_t * ui_Label7B;
lv_obj_t * ui_seatContainer1A;
lv_obj_t * ui_seatGUI1A;
lv_obj_t * ui_Label1A;
lv_obj_t * ui_seatContainer2A;
lv_obj_t * ui_seatGUI2A;
lv_obj_t * ui_Label2A;
lv_obj_t * ui_seatContainer3A;
lv_obj_t * ui_seatGUI3A;
lv_obj_t * ui_Label3A;
lv_obj_t * ui_seatContainer4A;
lv_obj_t * ui_seatGUI4A;
lv_obj_t * ui_Label4A;
lv_obj_t * ui_seatContainer5A;
lv_obj_t * ui_seatGUI5A;
lv_obj_t * ui_Label5A;
lv_obj_t * ui_seatContainer6A;
lv_obj_t * ui_seatGUI6A;
lv_obj_t * ui_Label6A;
lv_obj_t * ui_seatContainer7A;
lv_obj_t * ui_seatGUI7A;
lv_obj_t * ui_Label7A;
lv_obj_t * ui_seatContainer1H;
lv_obj_t * ui_seatGUI1H;
lv_obj_t * ui_Label1H;
lv_obj_t * ui_seatContainer2H;
lv_obj_t * ui_seatGUI2H;
lv_obj_t * ui_Label2H;
lv_obj_t * ui_seatContainer3H;
lv_obj_t * ui_seatGUI3H;
lv_obj_t * ui_Label3H;
lv_obj_t * ui_seatContainer4H;
lv_obj_t * ui_seatGUI4H;
lv_obj_t * ui_Label4H;
lv_obj_t * ui_seatContainer5H;
lv_obj_t * ui_seatGUI5H;
lv_obj_t * ui_Label5H;
lv_obj_t * ui_seatContainer6H;
lv_obj_t * ui_seatGUI6H;
lv_obj_t * ui_Label6H;
lv_obj_t * ui_seatContainer7H;
lv_obj_t * ui_seatGUI7H;
lv_obj_t * ui_Label7H;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image3;
// Top bar elements - LVGL-based (no PNG image)
lv_obj_t * ui_Top;
lv_obj_t * ui_Logo;
lv_obj_t * ui_BuckledBG;
lv_obj_t * ui_BuckledImg;
lv_obj_t * ui_BuckledSeatsLabel;
lv_obj_t * ui_BuckledLabel;
lv_obj_t * ui_UnbuckledBG;
lv_obj_t * ui_UnbuckledImg;
lv_obj_t * ui_UnuckledSeatsLabel;
lv_obj_t * ui_UnBuckledLabel;
lv_obj_t * ui_DoorBG;
lv_obj_t * ui_DoorImg;
lv_obj_t * ui_DoorStatusLabel;
lv_obj_t * ui_DoorLabel;
lv_obj_t * ui_occupancySlider;

lv_obj_t * ui_Door;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label4;

// Vehicle outline LVGL objects - Red borders (always visible)
lv_obj_t * ui_RedOutline7Full;
lv_obj_t * ui_RedOutline7Right;
lv_obj_t * ui_RedOutline7RightBorder;
lv_obj_t * ui_RedOutline7Left;
lv_obj_t * ui_RedOutline7LeftBorder;
lv_obj_t * ui_RedOutline4Full;
lv_obj_t * ui_RedOutline4Right;
lv_obj_t * ui_RedOutline4RightBorder;
lv_obj_t * ui_RedOutline4Left;
lv_obj_t * ui_RedOutline4LeftBorder;

// Vehicle outline LVGL objects - White overlays (shown when all safe)
lv_obj_t * ui_WhiteOutline7Full;
lv_obj_t * ui_WhiteOutline7Right;
lv_obj_t * ui_WhiteOutline7RightBorder;
lv_obj_t * ui_WhiteOutline7Left;
lv_obj_t * ui_WhiteOutline7LeftBorder;
lv_obj_t * ui_WhiteOutline4Full;
lv_obj_t * ui_WhiteOutline4Right;
lv_obj_t * ui_WhiteOutline4RightBorder;
lv_obj_t * ui_WhiteOutline4Left;
lv_obj_t * ui_WhiteOutline4LeftBorder;

lv_obj_t * ui_busWhBG;
lv_obj_t * ui_SbusWhBG;
lv_obj_t * ui____initial_actions0;

// Information Screen Objects - Memory Efficient Implementation
lv_obj_t * ui_InfoButton;
lv_obj_t * ui_SeatWarningLabel;
lv_obj_t * ui_MutedLabel;
lv_obj_t * ui_LogTabWarningIcon;
lv_obj_t * ui_InfoScreen;
lv_obj_t * ui_InfoBackButton;
lv_obj_t * ui_LogTextArea = NULL;
lv_obj_t * ui_LogCounterLabel = NULL;
lv_obj_t * ui_ClearLogButton = NULL;

// Individual info screens (only created when needed)
lv_obj_t * ui_AboutScreen = NULL;
lv_obj_t * ui_LogScreen = NULL;
lv_obj_t * ui_HelpScreen = NULL;
lv_obj_t * ui_DriveTypeScreen = NULL;
lv_obj_t * ui_BuzzerControlScreen = NULL;
lv_obj_t * ui_LHDButton;
lv_obj_t * ui_RHDButton;
// PNG arrays for migrated outline images removed (see MIGRATION_COMPLETE.md)
// const lv_img_dsc_t * ui_imgset_bus[3] = {&ui_img_bus5_png, &ui_img_bus6_png, &ui_img_bus7_png};
// const lv_img_dsc_t * ui_imgset_sbus[1] = {&ui_img_sbus1_png};
// const lv_img_dsc_t * ui_imgset_top[1] = {&ui_img_top4_png};  // Removed - top bar now uses LVGL elements
///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        toggleSide = true;
    }
}

// Information Button Event Handler
void ui_event_InfoButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_InfoScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_InfoScreen_screen_init);
    }
}

// Information Back Button Event Handler
void ui_event_InfoBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        // Don't reset ui_LogTextArea - LVGL objects persist in memory
        lv_scr_load_anim(ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, false);
    }
}

// LHD Button Event Handler (Left-Hand Drive)
void ui_event_LHDButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        // Only toggle if currently in RHD mode (rightActive is true)
        if (rightActive) {
            toggleSide = true;
        }

        // Style LHD button as selected (active state)
        lv_obj_set_style_bg_color(ui_LHDButton, lv_color_hex(0xEC1E45), LV_PART_MAIN | LV_STATE_DEFAULT);

        // Style RHD button as unselected (inactive state)
        lv_obj_set_style_bg_color(ui_RHDButton, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}

// RHD Button Event Handler (Right-Hand Drive)
void ui_event_RHDButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        // Only toggle if currently in LHD mode (leftActive is true)
        if (leftActive) {
            toggleSide = true;
        }

        // Style RHD button as selected (active state)
        lv_obj_set_style_bg_color(ui_RHDButton, lv_color_hex(0xEC1E45), LV_PART_MAIN | LV_STATE_DEFAULT);

        // Style LHD button as unselected (inactive state)
        lv_obj_set_style_bg_color(ui_LHDButton, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}

// New Event Handlers for Memory-Efficient Info Screens

// Back to Menu Handler
void ui_event_BackToMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        // Don't reset ui_LogTextArea - LVGL objects persist in memory
        _ui_screen_change(&ui_InfoScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_InfoScreen_screen_init);
    }
}

// About Button Handler
void ui_event_AboutButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_AboutScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_AboutScreen_screen_init);
    }
}

// Log Button Handler
void ui_event_LogButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        // Screen init now populates data synchronously (like buzzer screen)
        _ui_screen_change(&ui_LogScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_LogScreen_screen_init);
    }
}

// Help Button Handler
void ui_event_HelpButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HelpScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_HelpScreen_screen_init);
    }
}

// Clear Log Button Handler - Clears all error history
void ui_event_ClearLogButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        // Clear all errors using the helper function
        clearAllErrors();
    }
}

// Drive Type Button Handler
void ui_event_DriveTypeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DriveTypeScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_DriveTypeScreen_screen_init);
    }
}

// Row settings Button Handler
void ui_event_BuzzerControlButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_BuzzerControlScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_BuzzerControlScreen_screen_init);
    }
}

// Buzzer Toggle Button Handler (implementation moved to DisplayV9.ino)
// This is just a forward declaration - actual implementation is in the .ino file
void ui_event_BuzzerToggle(lv_event_t * e);

// Global flag for reset request (accessible from both C and C++)
extern bool uiResetRequested;

// Unified Reset Button Event Handler (Memory Optimized)
void ui_event_DuplicateErrorResetButton(lv_event_t * e)
{
    // Access external variables from DisplayV9.ino
    extern lv_obj_t *ui_DuplicateErrorResetButton;
    extern lv_obj_t *ui_DuplicateErrorResetLabel;

    static bool confirmReset = false;
    static uint32_t confirmTime = 0;

    if(lv_event_get_code(e) != LV_EVENT_CLICKED) return;

    uint32_t currentTime = millis();

    // Check timeout and reset if needed (3 seconds)
    if (confirmReset && (currentTime - confirmTime > 3000)) {
        confirmReset = false;
    }

    if (!confirmReset) {
        // First click - show confirmation
        if (ui_DuplicateErrorResetLabel) {
            lv_label_set_text(ui_DuplicateErrorResetLabel, "Confirm Reset");
            lv_obj_set_style_bg_color(ui_DuplicateErrorResetButton, lv_color_hex(0xEC1E45), LV_PART_MAIN);
            lv_obj_set_style_text_color(ui_DuplicateErrorResetLabel, lv_color_hex(0xFAFAFA), LV_PART_MAIN);
        }
        confirmReset = true;
        confirmTime = currentTime;
    } else {
        // Second click - trigger system reset
        // Logging is handled in main loop when uiResetRequested is processed
        uiResetRequested = true;
        confirmReset = false;
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
