// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_liteGreyBG;
extern lv_obj_t * ui_textLable;
extern lv_obj_t * ui_busBackBorder;
extern lv_obj_t * ui_seatContainerDriver;
extern lv_obj_t * ui_seatGUI;
extern lv_obj_t * ui_seatContainer1C;
extern lv_obj_t * ui_seatGUI1C;
extern lv_obj_t * ui_Label1C;
extern lv_obj_t * ui_seatContainer2C;
extern lv_obj_t * ui_seatGUI2C;
extern lv_obj_t * ui_Label2C;
extern lv_obj_t * ui_seatContainer4C;
extern lv_obj_t * ui_seatGUI4C;
extern lv_obj_t * ui_Label4C;
extern lv_obj_t * ui_seatContainer3C;
extern lv_obj_t * ui_seatGUI3C;
extern lv_obj_t * ui_Label3C;
extern lv_obj_t * ui_seatContainer5C;
extern lv_obj_t * ui_seatGUI5C;
extern lv_obj_t * ui_Label5C;
extern lv_obj_t * ui_seatContainer6C;
extern lv_obj_t * ui_seatGUI6C;
extern lv_obj_t * ui_Label6C;
extern lv_obj_t * ui_seatContainer7C;
extern lv_obj_t * ui_seatGUI7C;
extern lv_obj_t * ui_Label7C;
extern lv_obj_t * ui_seatContainer1B;
extern lv_obj_t * ui_seatGUI1B;
extern lv_obj_t * ui_Label1B;
extern lv_obj_t * ui_seatContainer2B;
extern lv_obj_t * ui_seatGUI2B;
extern lv_obj_t * ui_Label2B;
extern lv_obj_t * ui_seatContainer3B;
extern lv_obj_t * ui_seatGUI3B;
extern lv_obj_t * ui_Label3B;
extern lv_obj_t * ui_seatContainer4B;
extern lv_obj_t * ui_seatGUI4B;
extern lv_obj_t * ui_Label4B;
extern lv_obj_t * ui_seatContainer5B;
extern lv_obj_t * ui_seatGUI5B;
extern lv_obj_t * ui_Label5B;
extern lv_obj_t * ui_seatContainer6B;
extern lv_obj_t * ui_seatGUI6B;
extern lv_obj_t * ui_Label6B;
extern lv_obj_t * ui_seatContainer7B;
extern lv_obj_t * ui_seatGUI7B;
extern lv_obj_t * ui_Label7B;
extern lv_obj_t * ui_seatContainer1A;
extern lv_obj_t * ui_seatGUI1A;
extern lv_obj_t * ui_Label1A;
extern lv_obj_t * ui_seatContainer2A;
extern lv_obj_t * ui_seatGUI2A;
extern lv_obj_t * ui_Label2A;
extern lv_obj_t * ui_seatContainer3A;
extern lv_obj_t * ui_seatGUI3A;
extern lv_obj_t * ui_Label3A;
extern lv_obj_t * ui_seatContainer4A;
extern lv_obj_t * ui_seatGUI4A;
extern lv_obj_t * ui_Label4A;
extern lv_obj_t * ui_seatContainer5A;
extern lv_obj_t * ui_seatGUI5A;
extern lv_obj_t * ui_Label5A;
extern lv_obj_t * ui_seatContainer6A;
extern lv_obj_t * ui_seatGUI6A;
extern lv_obj_t * ui_Label6A;
extern lv_obj_t * ui_seatContainer7A;
extern lv_obj_t * ui_seatGUI7A;
extern lv_obj_t * ui_Label7A;
extern lv_obj_t * ui_seatContainer1H;
extern lv_obj_t * ui_seatGUI1H;
extern lv_obj_t * ui_Label1H;
extern lv_obj_t * ui_seatContainer2H;
extern lv_obj_t * ui_seatGUI2H;
extern lv_obj_t * ui_Label2H;
extern lv_obj_t * ui_seatContainer3H;
extern lv_obj_t * ui_seatGUI3H;
extern lv_obj_t * ui_Label3H;
extern lv_obj_t * ui_seatContainer4H;
extern lv_obj_t * ui_seatGUI4H;
extern lv_obj_t * ui_Label4H;
extern lv_obj_t * ui_seatContainer5H;
extern lv_obj_t * ui_seatGUI5H;
extern lv_obj_t * ui_Label5H;
extern lv_obj_t * ui_seatContainer6H;
extern lv_obj_t * ui_seatGUI6H;
extern lv_obj_t * ui_Label6H;
extern lv_obj_t * ui_seatContainer7H;
extern lv_obj_t * ui_seatGUI7H;
extern lv_obj_t * ui_Label7H;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image3;
// Top bar elements - LVGL-based (no PNG image)
extern lv_obj_t * ui_Top;
extern lv_obj_t * ui_Logo;
extern lv_obj_t * ui_BuckledBG;
extern lv_obj_t * ui_BuckledImg;
extern lv_obj_t * ui_BuckledSeatsLabel;
extern lv_obj_t * ui_BuckledLabel;
extern lv_obj_t * ui_UnbuckledBG;
extern lv_obj_t * ui_UnbuckledImg;
extern lv_obj_t * ui_UnuckledSeatsLabel;
extern lv_obj_t * ui_UnBuckledLabel;
extern lv_obj_t * ui_DoorBG;
extern lv_obj_t * ui_DoorImg;
extern lv_obj_t * ui_DoorStatusLabel;
extern lv_obj_t * ui_DoorLabel;
extern lv_obj_t * ui_occupancySlider;
extern lv_obj_t * ui_Door;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label4;

// Vehicle outline LVGL objects - Red borders (always visible)
extern lv_obj_t * ui_RedOutline7Full;
extern lv_obj_t * ui_RedOutline7Right;
extern lv_obj_t * ui_RedOutline7RightBorder;
extern lv_obj_t * ui_RedOutline7Left;
extern lv_obj_t * ui_RedOutline7LeftBorder;
extern lv_obj_t * ui_RedOutline4Full;
extern lv_obj_t * ui_RedOutline4Right;
extern lv_obj_t * ui_RedOutline4RightBorder;
extern lv_obj_t * ui_RedOutline4Left;
extern lv_obj_t * ui_RedOutline4LeftBorder;

// Vehicle outline LVGL objects - White overlays (shown when all safe)
extern lv_obj_t * ui_WhiteOutline7Full;
extern lv_obj_t * ui_WhiteOutline7Right;
extern lv_obj_t * ui_WhiteOutline7RightBorder;
extern lv_obj_t * ui_WhiteOutline7Left;
extern lv_obj_t * ui_WhiteOutline7LeftBorder;
extern lv_obj_t * ui_WhiteOutline4Full;
extern lv_obj_t * ui_WhiteOutline4Right;
extern lv_obj_t * ui_WhiteOutline4RightBorder;
extern lv_obj_t * ui_WhiteOutline4Left;
extern lv_obj_t * ui_WhiteOutline4LeftBorder;

extern lv_obj_t * ui_busWhBG;
extern lv_obj_t * ui_SbusWhBG;

extern lv_obj_t * ui____initial_actions0;

extern bool toggleSide;
extern bool toggleLayout;
extern bool rightActive;
extern bool leftActive;

// Information Screen Components - Memory Efficient Implementation
extern lv_obj_t * ui_InfoButton;
extern lv_obj_t * ui_SeatWarningLabel;
extern lv_obj_t * ui_MutedLabel;
extern lv_obj_t * ui_LogTabWarningIcon;
extern lv_obj_t * ui_InfoScreen;
extern lv_obj_t * ui_InfoBackButton;
extern lv_obj_t * ui_LogTextArea;
extern lv_obj_t * ui_LogCounterLabel;
extern lv_obj_t * ui_ClearLogButton;

// Individual info screens (only created when needed)
extern lv_obj_t * ui_AboutScreen;
extern lv_obj_t * ui_LogScreen;
extern lv_obj_t * ui_HelpScreen;
extern lv_obj_t * ui_DriveTypeScreen;
extern lv_obj_t * ui_BuzzerControlScreen;
extern lv_obj_t * ui_LHDButton;
extern lv_obj_t * ui_RHDButton;

// Event Handlers
void ui_event_InfoButton(lv_event_t * e);
void ui_event_InfoBackButton(lv_event_t * e);
void ui_event_BackToMenu(lv_event_t * e);
void ui_event_AboutButton(lv_event_t * e);
void ui_event_LogButton(lv_event_t * e);
void ui_event_HelpButton(lv_event_t * e);
void ui_event_DriveTypeButton(lv_event_t * e);
void ui_event_BuzzerControlButton(lv_event_t * e);
void ui_event_BuzzerToggle(lv_event_t * e);
void ui_event_LHDButton(lv_event_t * e);
void ui_event_RHDButton(lv_event_t * e);
void ui_event_ClearLogButton(lv_event_t * e);

// Screen initialization functions
void ui_InfoScreen_screen_init(void);
void ui_AboutScreen_screen_init(void);
void ui_LogScreen_screen_init(void);
void ui_HelpScreen_screen_init(void);
void ui_DriveTypeScreen_screen_init(void);
void ui_BuzzerControlScreen_screen_init(void);

// Event handlers
void ui_event_DuplicateErrorResetButton(lv_event_t * e);

// Warning icon management function
void updateAllWarningIcons(void);
void updateLogDisplay(void);
void clearAllErrors(void);

// Migrated PNG images removed - using LVGL objects instead (see MIGRATION_COMPLETE.md)
// LV_IMG_DECLARE(ui_img_bus7_png);    // Replaced with ui_RedOutline7Full
// LV_IMG_DECLARE(ui_img_sbus1_png);    // Replaced with ui_RedOutline4Full
// LV_IMG_DECLARE(ui_img_wh_bg_bus_png);    // Replaced with ui_WhiteOutline7Full
// LV_IMG_DECLARE(ui_img_wh_bg_sbus_png);    // Replaced with ui_WhiteOutline4Full

LV_IMG_DECLARE(ui_img_stearing_png);    // assets/stearing.png
LV_IMG_DECLARE(ui_img_bus5_png);    // assets/Bus5.png
LV_IMG_DECLARE(ui_img_bus6_png);    // assets/Bus6.png
// Top bar icon images
LV_IMG_DECLARE(ui_img_194055532);    // assets/logo.png
LV_IMG_DECLARE(ui_img_buk_icon_png);    // assets/buk_icon.png
LV_IMG_DECLARE(ui_img_unbk_icon_png);    // assets/unbk_icon.png
LV_IMG_DECLARE(ui_img_door_icon_png);    // assets/door_icon.png



LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font2);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
