// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// ==================== SEAT CREATION HELPER ====================
// Consolidated helper to reduce repetitive seat creation code
static void create_seat(lv_obj_t* parent, lv_obj_t** container, lv_obj_t** seatGUI, lv_obj_t** label,
                        int x, int y, int container_width, int container_height,
                        const char* label_text, lv_color_t bg_color, bool hidden)
{
    // Create container
    *container = lv_obj_create(parent);
    lv_obj_remove_style_all(*container);
    lv_obj_set_width(*container, container_width);
    lv_obj_set_height(*container, container_height);
    lv_obj_set_x(*container, x);
    lv_obj_set_y(*container, y);
    lv_obj_set_align(*container, LV_ALIGN_CENTER);
    if(hidden) lv_obj_add_flag(*container, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(*container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    // Create seatGUI (visual representation)
    *seatGUI = lv_obj_create(*container);
    lv_obj_remove_style_all(*seatGUI);
    lv_obj_set_width(*seatGUI, 85);
    lv_obj_set_height(*seatGUI, 68);
    lv_obj_set_align(*seatGUI, LV_ALIGN_CENTER);
    lv_obj_clear_flag(*seatGUI, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(*seatGUI, bg_color, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(*seatGUI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(*seatGUI, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(*seatGUI, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(*seatGUI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(*seatGUI, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create label
    *label = lv_label_create(*seatGUI);
    lv_obj_set_width(*label, LV_SIZE_CONTENT);
    lv_obj_set_height(*label, LV_SIZE_CONTENT);
    lv_obj_set_align(*label, LV_ALIGN_CENTER);
    lv_label_set_text(*label, label_text);
    lv_obj_set_style_text_color(*label, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(*label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(*label, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);
}

// ==================== VEHICLE OUTLINE HELPERS ====================
// Consolidated helpers to reduce repetitive outline creation code

// Helper to create a single outline border object (used for both Right and Left borders)
static void create_outline_border(lv_obj_t* parent, lv_obj_t** border,
                                   int width, int height, int x, int y,
                                   lv_align_t align, int radius, lv_color_t border_color)
{
    *border = lv_obj_create(parent);
    lv_obj_remove_style_all(*border);
    lv_obj_set_width(*border, width);
    lv_obj_set_height(*border, height);
    lv_obj_set_x(*border, x);
    lv_obj_set_y(*border, y);
    lv_obj_set_align(*border, align);
    lv_obj_set_style_radius(*border, radius, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(*border, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(*border, border_color, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(*border, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(*border, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(*border, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_clear_flag(*border, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
}

// Helper to create complete outline (Full container + Right/Left sides with borders)
static void create_vehicle_outline(lv_obj_t* parent,
                                    lv_obj_t** outlineFull, lv_obj_t** outlineRight, lv_obj_t** outlineRightBorder,
                                    lv_obj_t** outlineLeft, lv_obj_t** outlineLeftBorder,
                                    int full_width, int side_right_width, int side_left_width, int border_width,
                                    lv_color_t border_color, bool hidden)
{
    // Create Full container
    *outlineFull = lv_obj_create(parent);
    lv_obj_remove_style_all(*outlineFull);
    lv_obj_set_width(*outlineFull, full_width);
    lv_obj_set_height(*outlineFull, 311);
    lv_obj_set_align(*outlineFull, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(*outlineFull, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    // Create Right side container
    *outlineRight = lv_obj_create(*outlineFull);
    lv_obj_remove_style_all(*outlineRight);
    lv_obj_set_width(*outlineRight, side_right_width);
    lv_obj_set_height(*outlineRight, 325);
    lv_obj_set_align(*outlineRight, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(*outlineRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    // Create Right border
    create_outline_border(*outlineRight, outlineRightBorder, border_width, 285, -11, 1,
                          LV_ALIGN_RIGHT_MID, 20, border_color);

    // Create Left side container
    *outlineLeft = lv_obj_create(*outlineFull);
    lv_obj_remove_style_all(*outlineLeft);
    lv_obj_set_width(*outlineLeft, side_left_width);
    lv_obj_set_height(*outlineLeft, 325);
    lv_obj_set_align(*outlineLeft, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_clear_flag(*outlineLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

    // Create Left border
    create_outline_border(*outlineLeft, outlineLeftBorder, border_width, 285, 11, 1,
                          LV_ALIGN_LEFT_MID, 50, border_color);

    // Apply hidden flag if requested
    if(hidden) {
        lv_obj_add_flag(*outlineFull, LV_OBJ_FLAG_HIDDEN);
    }
}

void ui_Screen1_screen_init(void) {
  ui_Screen1 = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  ui_liteGreyBG = lv_obj_create(ui_Screen1);
  lv_obj_remove_style_all(ui_liteGreyBG);
  lv_obj_set_width(ui_liteGreyBG, 800);
  lv_obj_set_height(ui_liteGreyBG, 377);
  lv_obj_set_x(ui_liteGreyBG, 0);
  lv_obj_set_y(ui_liteGreyBG, 80);
  lv_obj_set_align(ui_liteGreyBG, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_liteGreyBG, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_bg_color(ui_liteGreyBG, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_liteGreyBG, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_textLable = lv_label_create(ui_Screen1);
  lv_obj_set_width(ui_textLable, LV_SIZE_CONTENT);   /// 1
  lv_obj_set_height(ui_textLable, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_textLable, -293);
  lv_obj_set_y(ui_textLable, -188);
  lv_obj_set_align(ui_textLable, LV_ALIGN_CENTER);
  lv_label_set_text(ui_textLable, "TEXT");
  lv_obj_set_style_text_color(ui_textLable, lv_color_hex(0xB8FF6E), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_textLable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_textLable, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);



  ui_busBackBorder = lv_obj_create(ui_Screen1);
  lv_obj_remove_style_all(ui_busBackBorder);
  lv_obj_set_width(ui_busBackBorder, 774);
  lv_obj_set_height(ui_busBackBorder, 284);
  lv_obj_set_x(ui_busBackBorder, -2);
  lv_obj_set_y(ui_busBackBorder, 75);
  lv_obj_set_align(ui_busBackBorder, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_busBackBorder, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  // Driver seat (no label)
  ui_seatContainerDriver = lv_obj_create(ui_busBackBorder);
  lv_obj_remove_style_all(ui_seatContainerDriver);
  lv_obj_set_width(ui_seatContainerDriver, 94);
  lv_obj_set_height(ui_seatContainerDriver, 62);
  lv_obj_set_x(ui_seatContainerDriver, -150);
  lv_obj_set_y(ui_seatContainerDriver, -101);
  lv_obj_set_align(ui_seatContainerDriver, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_seatContainerDriver, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

  ui_seatGUI = lv_obj_create(ui_seatContainerDriver);
  lv_obj_remove_style_all(ui_seatGUI);
  lv_obj_set_width(ui_seatGUI, 85);
  lv_obj_set_height(ui_seatGUI, 68);
  lv_obj_set_align(ui_seatGUI, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_seatGUI, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
  lv_obj_set_style_bg_color(ui_seatGUI, lv_color_hex(0xA6A6A6), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_seatGUI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_radius(ui_seatGUI, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_seatGUI, lv_color_hex(0x323232), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_seatGUI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_seatGUI, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

  // Row C seats (using consolidated helper)
  create_seat(ui_busBackBorder, &ui_seatContainer1C, &ui_seatGUI1C, &ui_Label1C, -55, -100, 95, 64, "1C", lv_color_hex(0xFAFAFA), false);
  create_seat(ui_busBackBorder, &ui_seatContainer2C, &ui_seatGUI2C, &ui_Label2C, 32, -100, 94, 64, "2C", lv_color_hex(0xFFFFFF), false);
  create_seat(ui_busBackBorder, &ui_seatContainer3C, &ui_seatGUI3C, &ui_Label3C, 119, -100, 94, 64, "3C", lv_color_hex(0xFFFFFF), false);
  create_seat(ui_busBackBorder, &ui_seatContainer4C, &ui_seatGUI4C, &ui_Label4C, 206, -100, 94, 64, "4C", lv_color_hex(0xFFFFFF), false);
  create_seat(ui_busBackBorder, &ui_seatContainer5C, &ui_seatGUI5C, &ui_Label5C, 157, -99, 94, 64, "5C", lv_color_hex(0xFFFFFF), true);
  create_seat(ui_busBackBorder, &ui_seatContainer6C, &ui_seatGUI6C, &ui_Label6C, 246, -99, 94, 64, "6C", lv_color_hex(0xFFFFFF), true);
  create_seat(ui_busBackBorder, &ui_seatContainer7C, &ui_seatGUI7C, &ui_Label7C, 335, -99, 94, 64, "7C", lv_color_hex(0xFFFFFF), true);

  // Row B seats (using consolidated helper)
  create_seat(ui_busBackBorder, &ui_seatContainer1B, &ui_seatGUI1B, &ui_Label1B, -55, -29, 94, 64, "1B", lv_color_hex(0xFFFFFF), false);
  create_seat(ui_busBackBorder, &ui_seatContainer2B, &ui_seatGUI2B, &ui_Label2B, 32, -29, 94, 64, "2B", lv_color_hex(0xFFFFFF), false);
  create_seat(ui_busBackBorder, &ui_seatContainer3B, &ui_seatGUI3B, &ui_Label3B, 119, -29, 94, 64, "3B", lv_color_hex(0xFFFFFF), false);
  create_seat(ui_busBackBorder, &ui_seatContainer4B, &ui_seatGUI4B, &ui_Label4B, 206, -29, 94, 64, "4B", lv_color_hex(0xFFFFFF), false);
  create_seat(ui_busBackBorder, &ui_seatContainer5B, &ui_seatGUI5B, &ui_Label5B, 157, -29, 94, 64, "5B", lv_color_hex(0xFFFFFF), true);
  create_seat(ui_busBackBorder, &ui_seatContainer6B, &ui_seatGUI6B, &ui_Label6B, 246, -29, 94, 64, "6B", lv_color_hex(0xFFFFFF), true);
  create_seat(ui_busBackBorder, &ui_seatContainer7B, &ui_seatGUI7B, &ui_Label7B, 335, -29, 94, 64, "7B", lv_color_hex(0xFFFFFF), true);

  // Row A seats (using consolidated helper)
  create_seat(ui_busBackBorder, &ui_seatContainer1A, &ui_seatGUI1A, &ui_Label1A, -146, 111, 84, 64, "1A", lv_color_hex(0xFFFFFF), false);
  create_seat(ui_busBackBorder, &ui_seatContainer2A, &ui_seatGUI2A, &ui_Label2A, 32, 111, 94, 64, "2A", lv_color_hex(0xFFFFFF), false);
  create_seat(ui_busBackBorder, &ui_seatContainer3A, &ui_seatGUI3A, &ui_Label3A, 119, 111, 94, 64, "3A", lv_color_hex(0xFFFFFF), false);
  create_seat(ui_busBackBorder, &ui_seatContainer4A, &ui_seatGUI4A, &ui_Label4A, 206, 111, 94, 64, "4A", lv_color_hex(0xFFFFFF), false);
  create_seat(ui_busBackBorder, &ui_seatContainer5A, &ui_seatGUI5A, &ui_Label5A, 157, 112, 94, 64, "5A", lv_color_hex(0xFFFFFF), true);
  create_seat(ui_busBackBorder, &ui_seatContainer6A, &ui_seatGUI6A, &ui_Label6A, 246, 112, 94, 64, "6A", lv_color_hex(0xFFFFFF), true);
  create_seat(ui_busBackBorder, &ui_seatContainer7A, &ui_seatGUI7A, &ui_Label7A, 335, 112, 94, 64, "7A", lv_color_hex(0xFFFFFF), true);

  // Row H seats (using consolidated helper)
  create_seat(ui_busBackBorder, &ui_seatContainer1H, &ui_seatGUI1H, &ui_Label1H, -55, 40, 94, 64, "1D", lv_color_hex(0xFAFAFA), false);
  create_seat(ui_busBackBorder, &ui_seatContainer2H, &ui_seatGUI2H, &ui_Label2H, 33, 40, 94, 64, "2D", lv_color_hex(0xFFFFFF), false);
  create_seat(ui_busBackBorder, &ui_seatContainer3H, &ui_seatGUI3H, &ui_Label3H, 120, 40, 94, 64, "3D", lv_color_hex(0xFFFFFF), false);
  create_seat(ui_busBackBorder, &ui_seatContainer4H, &ui_seatGUI4H, &ui_Label4H, 207, 40, 94, 64, "4D", lv_color_hex(0xFFFFFF), false);
  create_seat(ui_busBackBorder, &ui_seatContainer5H, &ui_seatGUI5H, &ui_Label5H, 155, 41, 94, 64, "5D", lv_color_hex(0xFFFFFF), true);
  create_seat(ui_busBackBorder, &ui_seatContainer6H, &ui_seatGUI6H, &ui_Label6H, 241, 41, 94, 64, "6D", lv_color_hex(0xFFFFFF), true);
  create_seat(ui_busBackBorder, &ui_seatContainer7H, &ui_seatGUI7H, &ui_Label7H, 336, 41, 94, 64, "7D", lv_color_hex(0xFFFFFF), true);

  // PNG images disabled - replaced with LVGL objects (see VEHICLE_OUTLINE_DESIGN.md)
  // ui_Image8 = lv_img_create(ui_Screen1);  //7 row bus outline
  // lv_img_set_src(ui_Image8, &ui_img_bus7_png);
  // lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 785
  // lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);  /// 297
  // lv_obj_set_x(ui_Image8, -3);
  // lv_obj_set_y(ui_Image8, 82);
  // lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
  // lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  // lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);                      /// Flags

  // ui_Image1 = lv_img_create(ui_Screen1);  //4 row bus outline
  // lv_img_set_src(ui_Image1, &ui_img_sbus1_png);
  // lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 516
  // lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);  /// 293
  // lv_obj_set_x(ui_Image1, -3);
  // lv_obj_set_y(ui_Image1, 82);
  // lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
  // lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  // lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  // Placeholder NULL assignments to maintain variable compatibility
  ui_Image8 = NULL;
  ui_Image1 = NULL;

  ui_Image3 = lv_img_create(ui_Screen1);
  lv_img_set_src(ui_Image3, &ui_img_stearing_png);
  lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 46
  lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);  /// 46
  lv_obj_set_x(ui_Image3, -215);
  lv_obj_set_y(ui_Image3, -21);
  lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);  /// Flags

  // ==================== TOP BAR - LVGL ELEMENTS ====================
  // Replaces ui_img_top4_png with structured LVGL container and elements
  ui_Top = lv_obj_create(ui_Screen1);
  lv_obj_remove_style_all(ui_Top);
  lv_obj_set_width(ui_Top, 800);
  lv_obj_set_height(ui_Top, 133);
  lv_obj_set_align(ui_Top, LV_ALIGN_TOP_MID);
  lv_obj_clear_flag(ui_Top, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
  lv_obj_set_style_bg_color(ui_Top, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Top, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  // Logo
  ui_Logo = lv_img_create(ui_Top);
  lv_img_set_src(ui_Logo, &ui_img_194055532);
  lv_obj_set_width(ui_Logo, LV_SIZE_CONTENT);
  lv_obj_set_height(ui_Logo, LV_SIZE_CONTENT);
  lv_obj_set_x(ui_Logo, -22);
  lv_obj_set_y(ui_Logo, 11);
  lv_obj_add_flag(ui_Logo, LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_Logo, LV_OBJ_FLAG_SCROLLABLE);
  lv_img_set_zoom(ui_Logo, 220);

  // Buckled container
  ui_BuckledBG = lv_obj_create(ui_Top);
  lv_obj_remove_style_all(ui_BuckledBG);
  lv_obj_set_width(ui_BuckledBG, 220);
  lv_obj_set_height(ui_BuckledBG, 75);
  lv_obj_set_x(ui_BuckledBG, 12);
  lv_obj_set_y(ui_BuckledBG, -8);
  lv_obj_set_align(ui_BuckledBG, LV_ALIGN_BOTTOM_LEFT);
  lv_obj_clear_flag(ui_BuckledBG, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
  lv_obj_set_style_radius(ui_BuckledBG, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_BuckledBG, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_BuckledBG, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_BuckledImg = lv_img_create(ui_BuckledBG);
  lv_img_set_src(ui_BuckledImg, &ui_img_buk_icon_png);
  lv_obj_set_width(ui_BuckledImg, LV_SIZE_CONTENT);
  lv_obj_set_height(ui_BuckledImg, LV_SIZE_CONTENT);
  lv_obj_set_x(ui_BuckledImg, -20);
  lv_obj_set_y(ui_BuckledImg, -23);
  lv_obj_add_flag(ui_BuckledImg, LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_BuckledImg, LV_OBJ_FLAG_SCROLLABLE);
  lv_img_set_zoom(ui_BuckledImg, 80);

  ui_BuckledSeatsLabel = lv_label_create(ui_BuckledBG);
  lv_obj_set_width(ui_BuckledSeatsLabel, LV_SIZE_CONTENT);
  lv_obj_set_height(ui_BuckledSeatsLabel, LV_SIZE_CONTENT);
  lv_obj_set_x(ui_BuckledSeatsLabel, -20);
  lv_obj_set_y(ui_BuckledSeatsLabel, -7);
  lv_obj_set_align(ui_BuckledSeatsLabel, LV_ALIGN_BOTTOM_RIGHT);
  lv_label_set_text(ui_BuckledSeatsLabel, "12");
  lv_obj_set_style_text_color(ui_BuckledSeatsLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_BuckledSeatsLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_BuckledSeatsLabel, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_BuckledLabel = lv_label_create(ui_BuckledBG);
  lv_obj_set_width(ui_BuckledLabel, LV_SIZE_CONTENT);
  lv_obj_set_height(ui_BuckledLabel, LV_SIZE_CONTENT);
  lv_obj_set_x(ui_BuckledLabel, 19);
  lv_obj_set_y(ui_BuckledLabel, -3);
  lv_obj_set_align(ui_BuckledLabel, LV_ALIGN_BOTTOM_LEFT);
  lv_label_set_text(ui_BuckledLabel, "Buckled");
  lv_obj_set_style_text_color(ui_BuckledLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_BuckledLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_BuckledLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

  // Unbuckled container
  ui_UnbuckledBG = lv_obj_create(ui_Top);
  lv_obj_remove_style_all(ui_UnbuckledBG);
  lv_obj_set_width(ui_UnbuckledBG, 254);
  lv_obj_set_height(ui_UnbuckledBG, 75);
  lv_obj_set_x(ui_UnbuckledBG, 245);
  lv_obj_set_y(ui_UnbuckledBG, -8);
  lv_obj_set_align(ui_UnbuckledBG, LV_ALIGN_BOTTOM_LEFT);
  lv_obj_clear_flag(ui_UnbuckledBG, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
  lv_obj_set_style_radius(ui_UnbuckledBG, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_UnbuckledBG, lv_color_hex(0xEE1C41), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_UnbuckledBG, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_UnbuckledImg = lv_img_create(ui_UnbuckledBG);
  lv_img_set_src(ui_UnbuckledImg, &ui_img_unbk_icon_png);
  lv_obj_set_width(ui_UnbuckledImg, LV_SIZE_CONTENT);
  lv_obj_set_height(ui_UnbuckledImg, LV_SIZE_CONTENT);
  lv_obj_set_x(ui_UnbuckledImg, -21);
  lv_obj_set_y(ui_UnbuckledImg, -24);
  lv_obj_add_flag(ui_UnbuckledImg, LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_UnbuckledImg, LV_OBJ_FLAG_SCROLLABLE);
  lv_img_set_zoom(ui_UnbuckledImg, 80);

  ui_UnuckledSeatsLabel = lv_label_create(ui_UnbuckledBG);
  lv_obj_set_width(ui_UnuckledSeatsLabel, LV_SIZE_CONTENT);
  lv_obj_set_height(ui_UnuckledSeatsLabel, LV_SIZE_CONTENT);
  lv_obj_set_x(ui_UnuckledSeatsLabel, -28);
  lv_obj_set_y(ui_UnuckledSeatsLabel, -7);
  lv_obj_set_align(ui_UnuckledSeatsLabel, LV_ALIGN_BOTTOM_RIGHT);
  lv_label_set_text(ui_UnuckledSeatsLabel, "6");
  lv_obj_set_style_text_color(ui_UnuckledSeatsLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_UnuckledSeatsLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_UnuckledSeatsLabel, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_UnBuckledLabel = lv_label_create(ui_UnbuckledBG);
  lv_obj_set_width(ui_UnBuckledLabel, LV_SIZE_CONTENT);
  lv_obj_set_height(ui_UnBuckledLabel, LV_SIZE_CONTENT);
  lv_obj_set_x(ui_UnBuckledLabel, 19);
  lv_obj_set_y(ui_UnBuckledLabel, -3);
  lv_obj_set_align(ui_UnBuckledLabel, LV_ALIGN_BOTTOM_LEFT);
  lv_label_set_text(ui_UnBuckledLabel, "Unbuckled");
  lv_obj_set_style_text_color(ui_UnBuckledLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_UnBuckledLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_UnBuckledLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

  // Door container
  ui_DoorBG = lv_obj_create(ui_Top);
  lv_obj_remove_style_all(ui_DoorBG);
  lv_obj_set_width(ui_DoorBG, 277);
  lv_obj_set_height(ui_DoorBG, 75);
  lv_obj_set_x(ui_DoorBG, 513);
  lv_obj_set_y(ui_DoorBG, -8);
  lv_obj_set_align(ui_DoorBG, LV_ALIGN_BOTTOM_LEFT);
  lv_obj_clear_flag(ui_DoorBG, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
  lv_obj_set_style_radius(ui_DoorBG, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_DoorBG, lv_color_hex(0xEE1C41), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_DoorBG, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DoorImg = lv_img_create(ui_DoorBG);
  lv_img_set_src(ui_DoorImg, &ui_img_door_icon_png);
  lv_obj_set_width(ui_DoorImg, LV_SIZE_CONTENT);
  lv_obj_set_height(ui_DoorImg, LV_SIZE_CONTENT);
  lv_obj_set_x(ui_DoorImg, -15);
  lv_obj_set_y(ui_DoorImg, -23);
  lv_obj_add_flag(ui_DoorImg, LV_OBJ_FLAG_ADV_HITTEST);
  lv_obj_clear_flag(ui_DoorImg, LV_OBJ_FLAG_SCROLLABLE);
  lv_img_set_zoom(ui_DoorImg, 100);

  ui_DoorStatusLabel = lv_label_create(ui_DoorBG);
  lv_obj_set_width(ui_DoorStatusLabel, LV_SIZE_CONTENT);
  lv_obj_set_height(ui_DoorStatusLabel, LV_SIZE_CONTENT);
  lv_obj_set_x(ui_DoorStatusLabel, -17);
  lv_obj_set_y(ui_DoorStatusLabel, -7);
  lv_obj_set_align(ui_DoorStatusLabel, LV_ALIGN_BOTTOM_RIGHT);
  lv_label_set_text(ui_DoorStatusLabel, "OPEN");
  lv_obj_set_style_text_color(ui_DoorStatusLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_DoorStatusLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_DoorStatusLabel, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DoorLabel = lv_label_create(ui_DoorBG);
  lv_obj_set_width(ui_DoorLabel, LV_SIZE_CONTENT);
  lv_obj_set_height(ui_DoorLabel, LV_SIZE_CONTENT);
  lv_obj_set_x(ui_DoorLabel, 19);
  lv_obj_set_y(ui_DoorLabel, -3);
  lv_obj_set_align(ui_DoorLabel, LV_ALIGN_BOTTOM_LEFT);
  lv_label_set_text(ui_DoorLabel, "Door");
  lv_obj_set_style_text_color(ui_DoorLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_DoorLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_DoorLabel, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_occupancySlider = lv_slider_create(ui_Screen1);
  lv_slider_set_range(ui_occupancySlider, 0, 30);
  lv_slider_set_value(ui_occupancySlider, 15, LV_ANIM_OFF);
  if (lv_slider_get_mode(ui_occupancySlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_occupancySlider, 0,
                                                                                               LV_ANIM_OFF);
  lv_obj_set_width(ui_occupancySlider, 800);
  lv_obj_set_height(ui_occupancySlider, 30);
  lv_obj_set_x(ui_occupancySlider, 0);
  lv_obj_set_y(ui_occupancySlider, -89);
  lv_obj_set_align(ui_occupancySlider, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_occupancySlider, LV_OBJ_FLAG_CLICKABLE);  /// Flags
  lv_obj_set_style_radius(ui_occupancySlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_occupancySlider, lv_color_hex(0xEC1E45), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_occupancySlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_radius(ui_occupancySlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_occupancySlider, lv_color_hex(0xFEFEFE), LV_PART_INDICATOR | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_occupancySlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

  lv_obj_set_style_bg_color(ui_occupancySlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_occupancySlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

  // White PNG images disabled - replaced with LVGL white outlines
  // ui_busWhBG = lv_img_create(ui_Screen1);
  // lv_img_set_src(ui_busWhBG, &ui_img_wh_bg_bus_png);
  // lv_obj_set_width(ui_busWhBG, LV_SIZE_CONTENT);   /// 1
  // lv_obj_set_height(ui_busWhBG, LV_SIZE_CONTENT);  /// 1
  // lv_obj_set_x(ui_busWhBG, -3);
  // lv_obj_set_y(ui_busWhBG, 82);
  // lv_obj_set_align(ui_busWhBG, LV_ALIGN_CENTER);
  // lv_obj_add_flag(ui_busWhBG, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  // lv_obj_clear_flag(ui_busWhBG, LV_OBJ_FLAG_SCROLLABLE);                      /// Flags

  // ui_SbusWhBG = lv_img_create(ui_Screen1);
  // lv_img_set_src(ui_SbusWhBG, &ui_img_wh_bg_sbus_png);
  // lv_obj_set_width(ui_SbusWhBG, LV_SIZE_CONTENT);   /// 1
  // lv_obj_set_height(ui_SbusWhBG, LV_SIZE_CONTENT);  /// 1
  // lv_obj_set_x(ui_SbusWhBG, -3);
  // lv_obj_set_y(ui_SbusWhBG, 82);
  // lv_obj_set_align(ui_SbusWhBG, LV_ALIGN_CENTER);
  // lv_obj_add_flag(ui_SbusWhBG, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
  // lv_obj_clear_flag(ui_SbusWhBG, LV_OBJ_FLAG_SCROLLABLE);                      /// Flags

  // Placeholder NULL assignments to maintain variable compatibility
  ui_busWhBG = NULL;
  ui_SbusWhBG = NULL;

  // ==================== RED OUTLINE OBJECTS - 7-SEATER ====================
  // Red outline 7-seater (hidden initially)
  create_vehicle_outline(ui_Screen1, &ui_RedOutline7Full, &ui_RedOutline7Right, &ui_RedOutline7RightBorder,
                         &ui_RedOutline7Left, &ui_RedOutline7LeftBorder,
                         800, 680, 644, 777, lv_color_hex(0xEE1C41), true);

  // ==================== RED OUTLINE OBJECTS - 4-SEATER ====================
  // Red outline 4-seater (visible by default)
  create_vehicle_outline(ui_Screen1, &ui_RedOutline4Full, &ui_RedOutline4Right, &ui_RedOutline4RightBorder,
                         &ui_RedOutline4Left, &ui_RedOutline4LeftBorder,
                         520, 440, 418, 505, lv_color_hex(0xEE1C41), false);

  // ==================== WHITE OUTLINE OBJECTS - 7-SEATER ====================
  // White outline 7-seater (hidden initially)
  create_vehicle_outline(ui_Screen1, &ui_WhiteOutline7Full, &ui_WhiteOutline7Right, &ui_WhiteOutline7RightBorder,
                         &ui_WhiteOutline7Left, &ui_WhiteOutline7LeftBorder,
                         800, 680, 644, 777, lv_color_hex(0xFAFAFA), true);

  // ==================== WHITE OUTLINE OBJECTS - 4-SEATER ====================
  // White outline 4-seater (hidden initially)
  create_vehicle_outline(ui_Screen1, &ui_WhiteOutline4Full, &ui_WhiteOutline4Right, &ui_WhiteOutline4RightBorder,
                         &ui_WhiteOutline4Left, &ui_WhiteOutline4LeftBorder,
                         520, 440, 418, 505, lv_color_hex(0xFAFAFA), true);

  // Door graphic - moved to end to ensure it appears on top
  ui_Door = lv_obj_create(ui_Screen1);
  lv_obj_remove_style_all(ui_Door);
  lv_obj_set_width(ui_Door, 83);
  lv_obj_set_height(ui_Door, 14);
  lv_obj_set_x(ui_Door, -57);
  lv_obj_set_y(ui_Door, 226);
  lv_obj_set_align(ui_Door, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Door, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
  lv_obj_set_style_radius(ui_Door, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_color(ui_Door, lv_color_hex(0xEC1E45), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Door, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  // Hamburger Menu Button (top-right) - Material Design Rounded circular icon button
  ui_InfoButton = lv_btn_create(ui_Screen1);
  lv_obj_set_width(ui_InfoButton, 40);
  lv_obj_set_height(ui_InfoButton, 40);  // 40px height for proper touch target
  lv_obj_set_x(ui_InfoButton, 753);
  lv_obj_set_y(ui_InfoButton, 7);
  lv_obj_set_style_radius(ui_InfoButton, 20, LV_PART_MAIN | LV_STATE_DEFAULT);  // Material Design Rounded: 20px = perfectly circular
  lv_obj_set_style_bg_opa(ui_InfoButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);  // Transparent bg
  lv_obj_set_style_border_width(ui_InfoButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);  // No border for Text buttons
  lv_obj_set_style_shadow_width(ui_InfoButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);  // No elevation

  // Pressed state: subtle opacity overlay
  lv_obj_set_style_bg_opa(ui_InfoButton, 31, LV_PART_MAIN | LV_STATE_PRESSED);  // 0.12 opacity overlay
  lv_obj_set_style_bg_color(ui_InfoButton, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_PRESSED);

  lv_obj_add_event_cb(ui_InfoButton, ui_event_InfoButton, LV_EVENT_CLICKED, NULL);

  // Hamburger Menu Lines (three horizontal lines)
  // Top line
  lv_obj_t* hamburgerLine1 = lv_obj_create(ui_InfoButton);
  lv_obj_remove_style_all(hamburgerLine1);
  lv_obj_set_width(hamburgerLine1, 24);
  lv_obj_set_height(hamburgerLine1, 3);
  lv_obj_set_x(hamburgerLine1, 0);
  lv_obj_set_y(hamburgerLine1, -8);
  lv_obj_set_align(hamburgerLine1, LV_ALIGN_CENTER);
  lv_obj_set_style_bg_color(hamburgerLine1, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(hamburgerLine1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_clear_flag(hamburgerLine1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

  // Middle line
  lv_obj_t* hamburgerLine2 = lv_obj_create(ui_InfoButton);
  lv_obj_remove_style_all(hamburgerLine2);
  lv_obj_set_width(hamburgerLine2, 24);
  lv_obj_set_height(hamburgerLine2, 3);
  lv_obj_set_x(hamburgerLine2, 0);
  lv_obj_set_y(hamburgerLine2, 0);
  lv_obj_set_align(hamburgerLine2, LV_ALIGN_CENTER);
  lv_obj_set_style_bg_color(hamburgerLine2, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(hamburgerLine2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_clear_flag(hamburgerLine2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

  // Bottom line
  lv_obj_t* hamburgerLine3 = lv_obj_create(ui_InfoButton);
  lv_obj_remove_style_all(hamburgerLine3);
  lv_obj_set_width(hamburgerLine3, 24);
  lv_obj_set_height(hamburgerLine3, 3);
  lv_obj_set_x(hamburgerLine3, 0);
  lv_obj_set_y(hamburgerLine3, 8);
  lv_obj_set_align(hamburgerLine3, LV_ALIGN_CENTER);
  lv_obj_set_style_bg_color(hamburgerLine3, lv_color_hex(0xFAFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(hamburgerLine3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_clear_flag(hamburgerLine3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

  // Seat Status Warning Circle (DISABLED - replaced with warning overlay)
  // Warning icon removed - now using full-screen warning overlay instead
  // The warning overlay shows error messages with Confirm and Reset buttons
  ui_SeatWarningLabel = NULL;  // Set to NULL to prevent crashes
  /*
  ui_SeatWarningLabel = lv_obj_create(ui_Screen1);
  lv_obj_set_width(ui_SeatWarningLabel, 34);   // Same height as menu icon
  lv_obj_set_height(ui_SeatWarningLabel, 34);  // Same height as menu icon
  lv_obj_set_x(ui_SeatWarningLabel, 710);      // 43 pixels to the left of menu icon (753 - 43)
  lv_obj_set_y(ui_SeatWarningLabel, 7);        // Same vertical position as menu icon
  lv_obj_set_style_radius(ui_SeatWarningLabel, 17, LV_PART_MAIN | LV_STATE_DEFAULT);  // Make it circular (radius = width/2)
  lv_obj_set_style_bg_color(ui_SeatWarningLabel, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT); // Orange warning color
  lv_obj_set_style_bg_opa(ui_SeatWarningLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_SeatWarningLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_add_flag(ui_SeatWarningLabel, LV_OBJ_FLAG_HIDDEN);  // Initially hidden
  lv_obj_clear_flag(ui_SeatWarningLabel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);

  // Exclamation mark inside the circle
  lv_obj_t* warningExclamation = lv_label_create(ui_SeatWarningLabel);
  lv_label_set_text(warningExclamation, "!");
  lv_obj_set_style_text_color(warningExclamation, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Black text
  lv_obj_set_style_text_font(warningExclamation, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);   // Bold exclamation
  lv_obj_align(warningExclamation, LV_ALIGN_CENTER, 0, 0);  // Center the exclamation mark
  lv_obj_clear_flag(warningExclamation, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
  */

  // Muted Label (to the left of warning icon, shows during buzzer delay)
  ui_MutedLabel = lv_label_create(ui_Screen1);
  lv_label_set_text(ui_MutedLabel, "Loading [20]");
  lv_obj_set_x(ui_MutedLabel, 610);      // 100 pixels to the left of warning icon (710 - 100)
  lv_obj_set_y(ui_MutedLabel, 13);       // Vertically aligned with warning icon center
  lv_obj_set_style_text_color(ui_MutedLabel, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT); // Orange color to match warning
  lv_obj_set_style_text_font(ui_MutedLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_add_flag(ui_MutedLabel, LV_OBJ_FLAG_HIDDEN);  // Initially hidden
  lv_obj_clear_flag(ui_MutedLabel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);
}
